### ISSUE TITLE
Not exposing devices as locks in HomeKit

### ISSUE THREAD

**Issue by nnance** [nnance/homebridge-august-locks#2]
It looks like the plugin is having issues identifying the locks as locks and wasn't providing any functionality, but was exposing them as devices in HomeKit.  @erngyver I was able to confirm this was a problem and should be resolved in version 1.6.0

**Comment by erngyver** [comment]
@nnance - Devices are showing in apple's home app as of 1.6.0. 

I do still see a few minor issues:

1.  Filtered devices still show in the homebridge UI + apple home app (or i'm not adding the id's correctly, Readme indicates i should observe device id's in logs, but i'm not seeing them, so i'm adding the serial numbers from the HB accessories page)
2. Device state in home app doesn't match direct homekit integration or physical state
3. devices don't seem to automatically update when homekit or physical state changes
4. I can't figure out how to filter an array of devices (2)

If it helps at all, what i'm trying to accomplish is:  I have 3 august locks, 2 of which are co-located with HomepodMini/AppleTv - Homekit connection works great. One is distant and connects to homekit through ios 12 ipad mini.  I'm intending to just set up that one leveraging the august wifi bridge do drop the dependancy on the old ipad

Happy to submit individual issues if that's merited.

**Comment by nnance** [comment]
@erngyver I have a very similar setup with 2 devices on one bridge and a third device in a different location.   It's certainly a bug that the device IDs aren't showing up in the log.  I will open an issue for that.   In terms of the device state that one is odd as mine have been working properly.
